# Generated by Django 4.2.7 on 2023-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modernwarfare2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernwarfare2data',
            name='user_name',
            field=models.CharField(default='Player', max_length=255),
        ),
    ]
